// types.js
export const FETCH_ABOUT_US_REQUEST = 'FETCH_ABOUT_US_REQUEST';
export const FETCH_ABOUT_US_SUCCESS = 'FETCH_ABOUT_US_SUCCESS';
export const FETCH_ABOUT_US_FAIL = 'FETCH_ABOUT_US_FAIL';

export const CLEAR_ERRORS= "CLEAR_ERRORS"