export const ALL_CARS_REQUEST= "ALL_CARS_REQUEST"
export const ALL_CARS_SUCCESS= "ALL_CARS_SUCCESS"
export const ALL_CARS_FAIL= "ALL_CARS_FAIL"

export const CARS_DETAILS_REQUEST= " CARS_DETAILS_REQUEST"
export const CARS_DETAILS_SUCCESS= "CARS_DETAILS_SUCCESS"
export const CARS_DETAILS_FAIL= "CARS_DETAILS_FAIL"




export const CLEAR_ERRORS= "CLEAR_ERRORS"