export const ADD_CONTRACT_REQUEST = 'ADD_CONTRACT_REQUEST';
export const ADD_CONTRACT_SUCCESS = 'ADD_CONTRACT_SUCCESS';
export const ADD_CONTRACT_FAILURE = 'ADD_CONTRACT_FAILURE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';